sudo: required
service: docker
dist: bionic

env:
  matrix:
  - SUITE=bionic ARCH=amd64

branches:
  only:
  - master

addons:
  apt:
    packages:
    - debootstrap
    - fakeroot
    - gnupg
    - kernel-wedge
    - postfix
    - qemu-user-static
    - schroot

install:
  - git clone git://kernel.ubuntu.com/ubuntu/kteam-tools ~/kteam-tools

before_script:
  - cat /proc/sys/fs/binfmt_misc/qemu-*

script:
  - sudo mkdir -p /usr3/chroots
  - sudo ~/kteam-tools/chroot-setup/make_chroot ${SUITE} ${ARCH}
  - sudo tar -C /usr3/chroots/${SUITE}-${ARCH} -zcpf ${TRAVIS_BUILD_DIR}/rootfs.tar.gz .
  - docker build -t vicamo/kteam-tools-chroots:${SUITE}-${ARCH} ${TRAVIS_BUILD_DIR}
